//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcone.Locadora.Sistema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluguel
    {
        public int Id { get; set; }
        public System.DateTime DataAluguel { get; set; }
        public System.DateTime DataDevolucao { get; set; }
        public int QuilometragemInicial { get; set; }
        public int QuilometragemFinal { get; set; }
        public int Carro_Id { get; set; }
        public int Cliente_Id { get; set; }
    
        public virtual Carro Carro { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
