//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcone.Locadora.Sistema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        public Carro()
        {
            this.Alugueis = new HashSet<Aluguel>();
        }
    
        public int Id { get; set; }
        public string Placa { get; set; }
        public string Modelo { get; set; }
        public int Ano { get; set; }
        public int Quilometragem { get; set; }
    
        public virtual ICollection<Aluguel> Alugueis { get; set; }
    }
}
