//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcone.Locadora.Sistema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Alugueis = new HashSet<Aluguel>();
            this.DadosCartaoCreditoes = new HashSet<DadosCartaoCredito>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public int Endereco_Id { get; set; }
    
        public virtual ICollection<Aluguel> Alugueis { get; set; }
        public virtual ICollection<DadosCartaoCredito> DadosCartaoCreditoes { get; set; }
        public virtual Endereco Endereco { get; set; }
    }
}
