//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcone.Locadora.Sistema.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosCartaoCredito
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public string NumeroCartao { get; set; }
        public string NomeCliente { get; set; }
        public string Validade { get; set; }
        public string CodigoSeguranca { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
